getwd()
setwd("C:/Users/user/Desktop/Covid 19 trends/Investigating-COVID-19-Virus-Trends")
read.csv("C:/Users/user/Desktop/Covid 19 trends/covid19.csv")
covid19<-read.csv("C:/Users/user/Desktop/Covid 19 trends/covid19.csv")
head(covid19)
dim(covid19)
colnames(covid19)
glimpse(covid19)
summary(covid19)
View(covid19)
covid19_Al_States<-subset(covid19,select=-Province_State)
covid19_Al_States
View(covid19_Al_States)
covid19_all_states_daily<-subset(covid19_Al_States, select = c(Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive))
View(covid19_all_states_daily)
covid19_all_states_daily<-group_by("Country_Region")
install.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
install.packages("lubridate")
library(lubridate)
install.packages("DT")
library(DT)
install.packages("scales")
library(scales)
install.packages("ggthemes")
library(ggthemes)
install.packages("tidyr")
library(tidyr)
install.packages("tidyverse")
library(tidyverse)
covid19_all_states_daily<-covid19_all_states_daily%>%group_by(Country_Region)
view(covid19_all_states_daily)
covid19_all_states_daily<-covid19_all_states_daily%>%group_by(Country_Region)%>%summarise(tested=sum(daily_tested),positive=sum(daily_positive), active=sum(active),hospitalized = sum(hospitalizedCurr))
covid19_all_states_daily_sum<-covid19_all_states_daily%>%arrange(tested)
covid19_all_states_daily_sum<-covid19_all_states_daily%>%arrange(desc(tested))
covid19_all_states_daily<-covid19_all_states_daily%>%group_by(Country_Region)%>%summarise(tested=sum(daily_tested),positive=sum(daily_positive), active=sum(active),hospitalized = sum(hospitalizedCurr))                                                             
view(covid19_all_states_daily_sum)
covid_top_10<-head(covid19_all_states_daily_sum,10)
covid_top_10
ratios<-(covid_top_10$positive/covid_top_10$tested)
view(ratios)
top_10_covid_states_with_ratios<-cbind(covid_top_10,ratios)
view(top_10_covid_states_with_ratios)
covid19_positivity_rate<-top_10_covid_states_with_ratios%>%arrange(desc(ratios))
view(covid19_positivity_rate)
question <- "Which countries have had the highest number of positive cases against the number of tests?"
answer <- c("Positive tested cases" =covid19_positivity_rate )
